// authReducer
export const UPDATE_USER = 'UPDATE_USER'

// noteReducer
export const UPDATE_USER_NOTES = 'UPDATE_USER_NOTES'
export const CHANGE_USER_NOTE = 'CHANGE_USER_NOTE'
export const REMOVE_USER_NOTE = 'REMOVE_USER_NOTE'
export const ADD_USER_NOTE = 'ADD_USER_NOTE'

export const UPDATE_SHARED_NOTES = 'UPDATE_SHARED_NOTES'
export const CHANGE_SHARED_NOTE = 'CHANGE_SHARED_NOTE'
export const REMOVE_SHARED_NOTE = 'REMOVE_SHARED_NOTE'
export const ADD_SHARED_NOTE = 'ADD_SHARED_NOTE'

// focusedNoteReducer
export const SHOW_FOCUSED_NOTE = 'SHOW_FOCUSED_NOTE'
export const HIDE_FOCUSED_NOTE = 'HIDE_FOCUSED_NOTE'
export const UPDATE_FOCUSED_NOTE = 'UPDATE_FOCUSED_NOTE'
